import type { ExternalJobSource } from "@aijobs/types";

export type TargetCompany = {
  id: string;
  company: string;
  domain: string;
  homepage: string;
  careersUrl: string;
  segments: string[];
  priorityTier: "P1" | "P2" | "P3";
  expectedSource: ExternalJobSource;
};

const TARGET_COMPANIES: TargetCompany[] = [
  {
    id: "anthropic",
    company: "Anthropic",
    domain: "anthropic.com",
    homepage: "https://www.anthropic.com",
    careersUrl: "https://job-boards.greenhouse.io/anthropic",
    segments: ["ai", "software engineering", "product", "design"],
    priorityTier: "P1",
    expectedSource: "greenhouse",
  },
  {
    id: "databricks",
    company: "Databricks",
    domain: "databricks.com",
    homepage: "https://www.databricks.com",
    careersUrl: "https://job-boards.greenhouse.io/databricks",
    segments: ["data", "software engineering", "product", "design"],
    priorityTier: "P1",
    expectedSource: "greenhouse",
  },
  {
    id: "discord",
    company: "Discord",
    domain: "discord.com",
    homepage: "https://discord.com",
    careersUrl: "https://job-boards.greenhouse.io/discord",
    segments: ["consumer", "software engineering", "product", "design"],
    priorityTier: "P1",
    expectedSource: "greenhouse",
  },
  {
    id: "coinbase",
    company: "Coinbase",
    domain: "coinbase.com",
    homepage: "https://www.coinbase.com",
    careersUrl: "https://job-boards.greenhouse.io/coinbase",
    segments: ["fintech", "software engineering", "product", "design"],
    priorityTier: "P1",
    expectedSource: "greenhouse",
  },
  {
    id: "doordash",
    company: "DoorDash",
    domain: "doordash.com",
    homepage: "https://www.doordash.com",
    careersUrl: "https://job-boards.greenhouse.io/doordash",
    segments: ["marketplace", "software engineering", "product", "design"],
    priorityTier: "P1",
    expectedSource: "greenhouse",
  },
  {
    id: "scale-ai",
    company: "Scale AI",
    domain: "scale.com",
    homepage: "https://scale.com",
    careersUrl: "https://job-boards.greenhouse.io/scaleai",
    segments: ["ai", "software engineering", "product", "design"],
    priorityTier: "P1",
    expectedSource: "greenhouse",
  },
  {
    id: "perplexity",
    company: "Perplexity",
    domain: "perplexity.ai",
    homepage: "https://www.perplexity.ai",
    careersUrl: "https://job-boards.greenhouse.io/perplexityai",
    segments: ["ai", "software engineering", "product", "design"],
    priorityTier: "P1",
    expectedSource: "greenhouse",
  },
  {
    id: "instacart",
    company: "Instacart",
    domain: "instacart.com",
    homepage: "https://www.instacart.com",
    careersUrl: "https://job-boards.greenhouse.io/instacart",
    segments: ["marketplace", "software engineering", "product", "design"],
    priorityTier: "P1",
    expectedSource: "greenhouse",
  },
  {
    id: "roblox",
    company: "Roblox",
    domain: "roblox.com",
    homepage: "https://www.roblox.com",
    careersUrl: "https://job-boards.greenhouse.io/roblox",
    segments: ["gaming", "software engineering", "product", "design", "qa"],
    priorityTier: "P1",
    expectedSource: "greenhouse",
  },
  {
    id: "mongodb",
    company: "MongoDB",
    domain: "mongodb.com",
    homepage: "https://www.mongodb.com",
    careersUrl: "https://job-boards.greenhouse.io/mongodb",
    segments: ["developer tools", "software engineering", "product", "design"],
    priorityTier: "P1",
    expectedSource: "greenhouse",
  },
  {
    id: "cloudflare",
    company: "Cloudflare",
    domain: "cloudflare.com",
    homepage: "https://www.cloudflare.com",
    careersUrl: "https://job-boards.greenhouse.io/cloudflare",
    segments: ["security", "software engineering", "product", "design"],
    priorityTier: "P1",
    expectedSource: "greenhouse",
  },
  {
    id: "gitlab",
    company: "GitLab",
    domain: "gitlab.com",
    homepage: "https://about.gitlab.com",
    careersUrl: "https://job-boards.greenhouse.io/gitlab",
    segments: ["developer tools", "software engineering", "product", "design"],
    priorityTier: "P1",
    expectedSource: "greenhouse",
  },
  {
    id: "airtable",
    company: "Airtable",
    domain: "airtable.com",
    homepage: "https://www.airtable.com",
    careersUrl: "https://job-boards.greenhouse.io/airtable",
    segments: ["productivity", "software engineering", "product", "design"],
    priorityTier: "P1",
    expectedSource: "greenhouse",
  },
  {
    id: "lyft",
    company: "Lyft",
    domain: "lyft.com",
    homepage: "https://www.lyft.com",
    careersUrl: "https://job-boards.greenhouse.io/lyft",
    segments: ["mobility", "software engineering", "product", "design"],
    priorityTier: "P1",
    expectedSource: "greenhouse",
  },
  {
    id: "epic-games",
    company: "Epic Games",
    domain: "epicgames.com",
    homepage: "https://www.epicgames.com",
    careersUrl: "https://job-boards.greenhouse.io/epicgames",
    segments: ["gaming", "software engineering", "design", "qa"],
    priorityTier: "P1",
    expectedSource: "greenhouse",
  },
  {
    id: "netflix",
    company: "Netflix",
    domain: "netflix.com",
    homepage: "https://www.netflix.com",
    careersUrl: "https://jobs.lever.co/netflix",
    segments: ["consumer", "software engineering", "product", "design"],
    priorityTier: "P1",
    expectedSource: "lever",
  },
  {
    id: "atlassian",
    company: "Atlassian",
    domain: "atlassian.com",
    homepage: "https://www.atlassian.com",
    careersUrl: "https://jobs.lever.co/atlassian",
    segments: ["developer tools", "software engineering", "product", "design", "qa"],
    priorityTier: "P1",
    expectedSource: "lever",
  },
  {
    id: "attentive",
    company: "Attentive",
    domain: "attentive.com",
    homepage: "https://www.attentive.com",
    careersUrl: "https://jobs.lever.co/attentive",
    segments: ["marketing tech", "software engineering", "product", "design"],
    priorityTier: "P2",
    expectedSource: "lever",
  },
  {
    id: "openai",
    company: "OpenAI",
    domain: "openai.com",
    homepage: "https://openai.com",
    careersUrl: "https://jobs.ashbyhq.com/openai",
    segments: ["ai", "software engineering", "product", "design"],
    priorityTier: "P1",
    expectedSource: "ashby",
  },
  {
    id: "linear",
    company: "Linear",
    domain: "linear.app",
    homepage: "https://linear.app",
    careersUrl: "https://jobs.ashbyhq.com/linear",
    segments: ["productivity", "software engineering", "product", "design"],
    priorityTier: "P1",
    expectedSource: "ashby",
  },
  {
    id: "cursor",
    company: "Cursor",
    domain: "cursor.com",
    homepage: "https://cursor.com",
    careersUrl: "https://jobs.ashbyhq.com/cursor",
    segments: ["ai", "developer tools", "software engineering", "product", "design"],
    priorityTier: "P1",
    expectedSource: "ashby",
  },
  {
    id: "deel",
    company: "Deel",
    domain: "deel.com",
    homepage: "https://www.deel.com",
    careersUrl: "https://jobs.ashbyhq.com/deel",
    segments: ["hr tech", "software engineering", "product", "design"],
    priorityTier: "P1",
    expectedSource: "ashby",
  },
  {
    id: "vercel",
    company: "Vercel",
    domain: "vercel.com",
    homepage: "https://vercel.com",
    careersUrl: "https://jobs.ashbyhq.com/vercel",
    segments: ["developer tools", "software engineering", "product", "design"],
    priorityTier: "P1",
    expectedSource: "ashby",
  },
  {
    id: "snowflake",
    company: "Snowflake",
    domain: "snowflake.com",
    homepage: "https://www.snowflake.com",
    careersUrl: "https://jobs.ashbyhq.com/snowflake",
    segments: ["data", "software engineering", "product", "design"],
    priorityTier: "P1",
    expectedSource: "ashby",
  },
  {
    id: "harvey",
    company: "Harvey",
    domain: "harvey.ai",
    homepage: "https://www.harvey.ai",
    careersUrl: "https://jobs.ashbyhq.com/harvey",
    segments: ["ai", "software engineering", "product", "design"],
    priorityTier: "P1",
    expectedSource: "ashby",
  },
  {
    id: "clay",
    company: "Clay",
    domain: "clay.com",
    homepage: "https://www.clay.com",
    careersUrl: "https://jobs.ashbyhq.com/claylabs",
    segments: ["sales tech", "software engineering", "product", "design"],
    priorityTier: "P1",
    expectedSource: "ashby",
  },
  {
    id: "shopify",
    company: "Shopify",
    domain: "shopify.com",
    homepage: "https://www.shopify.com",
    careersUrl: "https://jobs.ashbyhq.com/shopify",
    segments: ["commerce", "software engineering", "product", "design"],
    priorityTier: "P1",
    expectedSource: "ashby",
  },
  {
    id: "posthog",
    company: "PostHog",
    domain: "posthog.com",
    homepage: "https://posthog.com",
    careersUrl: "https://jobs.ashbyhq.com/posthog",
    segments: ["developer tools", "software engineering", "product", "design"],
    priorityTier: "P2",
    expectedSource: "ashby",
  },
  {
    id: "supabase",
    company: "Supabase",
    domain: "supabase.com",
    homepage: "https://supabase.com",
    careersUrl: "https://jobs.ashbyhq.com/supabase",
    segments: ["developer tools", "software engineering", "product", "design"],
    priorityTier: "P2",
    expectedSource: "ashby",
  },
  {
    id: "raycast",
    company: "Raycast",
    domain: "raycast.com",
    homepage: "https://www.raycast.com",
    careersUrl: "https://jobs.ashbyhq.com/raycast",
    segments: ["productivity", "software engineering", "design"],
    priorityTier: "P2",
    expectedSource: "ashby",
  },
  {
    id: "render",
    company: "Render",
    domain: "render.com",
    homepage: "https://render.com",
    careersUrl: "https://jobs.ashbyhq.com/render",
    segments: ["cloud", "software engineering", "product", "design"],
    priorityTier: "P2",
    expectedSource: "ashby",
  },
  {
    id: "modern-treasury",
    company: "Modern Treasury",
    domain: "moderntreasury.com",
    homepage: "https://www.moderntreasury.com",
    careersUrl: "https://jobs.ashbyhq.com/moderntreasury",
    segments: ["fintech", "software engineering", "product", "design"],
    priorityTier: "P2",
    expectedSource: "ashby",
  },
  {
    id: "runway",
    company: "Runway",
    domain: "runwayml.com",
    homepage: "https://runwayml.com",
    careersUrl: "https://jobs.ashbyhq.com/runway-ml",
    segments: ["ai", "software engineering", "product", "design"],
    priorityTier: "P2",
    expectedSource: "ashby",
  },
  {
    id: "baseten",
    company: "Baseten",
    domain: "baseten.co",
    homepage: "https://www.baseten.co",
    careersUrl: "https://jobs.ashbyhq.com/baseten",
    segments: ["ai", "cloud", "software engineering", "product"],
    priorityTier: "P2",
    expectedSource: "ashby",
  },
];

export function getTargetCompanies() {
  return TARGET_COMPANIES;
}

export function getTargetCompanyById(id: string) {
  return TARGET_COMPANIES.find((company) => company.id === id);
}
